Prabandh/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('user/',include('User.urls')),
    path('',include('Rent.urls')),
    path('user/',include('User.urls')),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rent/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name="home"),
    path('product/',views.Productform,name="product"),
    path('ajax/load_subcat/', views.load_subcat, name='ajax_load_subcat'),
    path('cart/',views.cart,name="cart"),
    path('noti/',views.Issue,name="issue"),
    path('update/<my_id>',views.update,name="update"),
    path('issue/<my_id>',views.issueform,name="issueform"),
    path('rentedProduct', views.rentprod, name="rentprod"),
    path('Onrent', views.putrent, name="putrent"),
    path('cartdel/<my_id>',views.cartdel,name="cartdel"),
    path('cartadd/<my_id>',views.cartadd,name="cartadd"),
    path('Image/<prod_id>',views.Prod_view,name="Prod_view"),
    path("NewImage/",views.NewImage,name="NewImage"),
    path('event/<my_id>/<mysubcat>/<my_id1>',views.search_subcat,name="Search subcat"),
    path('Image/',views.load,name="load"),
    path('deleteImage/',views.deleteImage,name="Delete Image"),
    path('subcategory/<str:mysubcat1>/', views.search_subcat1, name="Search subcat1"),
    path('search/<my_id>', views.search_subcat1, name="search"),
    path('check/',views.Check.as_view(),name="check"),
    path('check/create/',views.create_payment,name="create"),
    path('webhook/',views.webhook,name="web"),
    path('success/',views.success.as_view(),name="success"),
    path('details/',views.RentAmt,name="detail"),
    path('booking/',views.rentprod,name="booking"),
    path('putrent/',views.putrent,name="putrent"),
    path('rate/<my_id>',views.rate,name="rate")
]

User/urls.py
from django.urls import path,include
from .views import Register
from User import views as user_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',user_views.Register,name="register"),
    path('profile/',user_views.profile,name="profile"),
    path('seller/',user_views.SellerView,name="seller"),
    path('login/',auth_views.LoginView.as_view(template_name='User\login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='Rent\home_page.html'),name='logout'),
]

User/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator,MinLengthValidator
# Create your models here.
class Profile(models.Model):

    user=models.OneToOneField(User,related_name='profile', on_delete=models.CASCADE)
    bank_acc_no=models.CharField(max_length=16,validators=[MinLengthValidator(16)])
    ifsc=models.CharField(max_length=11,validators=[MinLengthValidator(11)])
    address=models.TextField()
    seller=models.BooleanField(default=False)
    

    def __str__(self):
        return self.user.username

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

class Seller (models.Model):
    seller=models.OneToOneField(User,on_delete=models.CASCADE)
    name_of_business=models.CharField(max_length=50)
    gst_no=models.CharField(max_length=15,validators=[MinLengthValidator(15)])
    mobile_no=models.CharField(max_length=10,validators=[MinLengthValidator(10)])
    city=models.CharField(max_length=15)
    PAN=models.CharField(max_length=10,validators=[MinLengthValidator(10)])
    

    def __str__(self):
        return self.seller.username

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

User/forms.py
from django import forms
from .models import Profile,Seller
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from captcha.fields import CaptchaField


class RegisterForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model=Profile
        fields=('bank_acc_no','ifsc','address','seller','captcha')
        widgets={
            'bank_acc_no': forms.NumberInput(attrs={'class':'form-control textinput'}),
            'ifsc': forms.TextInput(attrs={'class':'form-control textinput'}),
            'address': forms.Textarea(attrs={'class':'form-control textinput textareaclass','rows':'3'}),
            'seller':forms.CheckboxInput(attrs={'class':'form-check-input','onclick':'changeText()'}),
            'captcha':forms.TextInput(attrs={'class':'form-control'})
        }
    
class UserForm(UserCreationForm):
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class':'form-control textinput', 'type':'password', 'align':'center',}),
    )
    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(attrs={'class':'form-control textinput', 'type':'password', 'align':'center',}),
    )

    class Meta:
        model=User
        # forms.EmailField(, required=False)
        fields=('username','email')
        widgets={
            'username': forms.TextInput(attrs={'class':'form-control textinput','onfocus':'move()','autocomplete':'off'}),
            'email': forms.TextInput(attrs={'class':'form-control textinput','type':'email','onclick':'move()'}),
        }

class SellerForm(forms.ModelForm):
    class Meta:
        model=Seller
        exclude=('seller',)
        widgets={
            'name_of_business':forms.TextInput(attrs={'class':'form-control textinput'}),
            'gst_no':forms.TextInput(attrs={'class':'form-control textinput'}),
            'mobile_no':forms.NumberInput(attrs={'class':'form-control textinput'}),
            'city':forms.TextInput(attrs={'class':'form-control textinput'}),
            'PAN':forms.TextInput(attrs={'class':'form-control textinput'}),
        }
    

User/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic import CreateView
from django.contrib.auth.models import User
from .forms import RegisterForm,UserForm,SellerForm
from User.models import Profile
from .models import Seller

# Create your views here.

def Register(request):
    if request.method=='POST':
        form=UserForm(request.POST)
        rform=RegisterForm(request.POST)
        if form.is_valid() and rform.is_valid():
            user=form.save()
            pro=rform.save(commit=False)
            isSeller=rform.cleaned_data['seller']
            print(isSeller)
            pro.user=user
            request.session['user']=user.username
            pro.save()
            if isSeller:
                return redirect('seller')
            else:
                return redirect('home')
        else:
            print(form.errors)
            return render(request,'User/register.html',{'user':form,'register':rform})

    else:
        # print(form.errors)
        form=UserForm()
    return render(request,'User/register.html',{'user':UserForm,'register':RegisterForm})

def SellerView(request):
        if request.method=='POST':
            form=SellerForm(request.POST)
            if form.is_valid():
                if 'user' in request.session:
                    user=request.session['user']
                    u=User.objects.get(username=user)
                else:
                    user=request.user.username
                    u=User.objects.get(username=user)
                    p=Profile.objects.filter(user=u)
                    p.update(seller=True)
                p=form.save(commit=False)
                p.seller=u
                p.save()
                return redirect('product')
            else:
                return render(request,'User/seller.html',{'user':form})
        else:
            form=SellerForm()
        return render(request,'User/seller.html',{'user':SellerForm})

def profile(request):
    user = request.user
    print(user)
    u = User.objects.get(username=user)
    Profiles = Profile.objects.filter(user=u)
    isSeller=Profile.objects.get(user=u).seller
    print(isSeller)
    print(Profiles)
    param_profile = {
        'Profile' : Profiles,
        'u':isSeller
    }
    return render(request,'User/profile.html',param_profile)

User/templates/User/add_rent.html
{% extends 'User/profile.html' %}

{% load static %}

{% block title %}
<link rel="stylesheet" href="{% static 'User/css/profile.css' %}">

{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(268deg, #0000ff, #00f0add9);
    }
    .user:hover {
        color: white;
    }
    .user{
        color: black; 
        text-shadow: 1px 1px 2px black, 0 0 25px red, 0 0 5px yellow;
    }    
</style>

<body>
    <div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
            <div class="col-md-4 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    <h1 class="font-weight-bold user">{{user}}</h1>
                    <span> </span>
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/user/profile/" class="text-decoration-none" target="_self">
                                    Profile </a></h4>
                        </div>

                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/booking/" class="text-decoration-none"> Bookings </a></h4>
                        </div>

                        {% if us %}                        
                        
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/putrent/" class="text-decoration-none"> Add for Rent </a></h4>
                        </div> 
                        
                        {% endif %}
                        
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/cart/" class="text-decoration-none"> Cart </a></h4>
                        </div>
                        
                    </div>
                </div>
                
            </div>
            
            
            <div class="col-md">
                <div class="p-3 py-5">
                    
                    <!-- Profile Section -->
                    <div>
                        <a class="btn btn-primary float" href="/product/" role="button">Add Item</a>
                        {% for i in product %}
                        <div class="card mb-3 border-bottom" style="max-width: 540px;">
                            <div class="row g-0 border-bottom">
                                <div class="col-md-3 col-sm-4">
                                    <img src='/media/{{i.image_of_product}}' class="img-fluid me-2" alt="...">
                                </div>
                                <div class="col-md-9 col-sm-8">
                                    <div class="card-body">
                                        <h5 class="card-title">{{i.title}}</h5>
                                        <div id="ca">
                                            {{i.score}}
                                        </div>
                                        <span class="fa fa-star checked" id="first"></span>
                                        <span class="fa fa-star checked" id="second"></span>
                                        <span class="fa fa-star checked" id="third"></span>
                                        <span class="fa fa-star" id="fourth"></span>
                                        <span class="fa fa-star" id="fifth"></span>

                                        <p class="card-text">
                                            {{i.about}}<BR>Rent Price: {{i.rental_price}}</BR>
                                            Deposit:{{i.deposit}}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}    
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock%}

User/templates/User/basic.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PRABANDH</title>
  <title>PRABANDH</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://unpkg.com/feather-icons"></script>
  {% block headjs %}
  {% endblock %}
      
  {% block css %}
  <style>
  .navbar{
  background-color:darkblue;
  }
  </style>
  {% endblock css %}
</head>

  <body>
      <nav class="navbar navbar-dark " style="background-color:darkblue;">
          <div class="container-fluid">
            <div class="me-4 mx-3">
              

              {% comment %} <img src="../../static/User/images/Prabandh.png" class="logo_image" alt="" srcset=""> {% endcomment %}
              <b>
              <a href="/" class="navbar-brand" style="color: white; text-shadow: 1px 1px 2px black, 0 0 25px red, 0 0 5px yellow;">
              PRABANDH</a>
                </b>
            
            </div>
            <form class="d-flex" method='get' action='/search/1'>
              <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="search" id="search">

              <button class="btn btn-outline-warning" type="submit" ><a href="/search/1" style="color:white; text-decoration: none;" >Search </a></button>
            </form>

            
            <div class="color">
              <a href="/noti" style="color:white;text-decoration:none;" class="mx-2"><i data-feather="bell"></i>({{k}})</a>

              {% if user.is_authenticated %}

                <a href="/user/profile" class="text-decoration-none" style="color: white">Welcome, {{user}}</a>
                <a href="/user/logout" class="text-decoration-none mx-2" style="color: white">logout</a>

              {% else %}
                
                <a href="/user/" class="text-decoration-none" style="color: white">Sign Up</a>
                <span style="color: white">/</span>
                <a href="/user/login" class="text-decoration-none" style="color: white">Login</a>

              {% endif %}
            </div>
          </div>
      </nav>
{% block nav %}
{% endblock  %}
  {% block content %}{% endblock %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

        {% block js %}
    <script>
      feather.replace()
    </script>
        {% endblock js %}
    </body>
</html>

User/templates/User/booking.html
{% extends 'User/profile.html' %}

{% load static %}

{% block title %}
    <link rel="stylesheet" href="{% static 'User/css/profile.css' %}">

{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(268deg, #0000ff, #00f0add9);
    }
    .user:hover {
        color: white;
    }
    .user{
        color: black; 
        text-shadow: 1px 1px 2px black, 0 0 25px red, 0 0 5px yellow;
    }
</style>
<body>
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row">
                <div class="col-md-4 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                        <h1 class="font-weight-bold user">{{user}}</h1>
                        <span> </span>
                                            <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/user/profile" class="text-decoration-none"
                                    target="_self">Profile </a></h4>
                        </div>


                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/booking/" class="text-decoration-none"> Bookings </a></h4>
                        </div>

                        {% if us %}                        
                        
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/putrent/" class="text-decoration-none"> Add for Rent </a></h4>
                        </div> 
                        
                        {% endif %}

                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right"><a href="/cart/" class="text-decoration-none"> Cart </a></h4>
                        </div>

                    </div>
                   </div>

                </div>
            
            
                <div class="col-md">
                    <div class="p-3 py-5">

                        <!-- Profile Section -->
                        <div>
            {% for i in product %}
            <div class="card mb-3 border-bottom" style="max-width: 540px;">
              <div class="row g-0 border-bottom">
                <div class="col-md-3 col-sm-4">
                  <img src='/media/{{i.image_of_product}}' class="img-fluid me-2" alt="...">
                </div>
                <div class="col-md-9 col-sm-8">
                    <div class="card-body">
                      <h5 class="card-title">{{i.title}}</h5>
                          <div id="ca">
                              {{i.score}}
                          </div>
                            <span class="fa fa-star checked" id="first"></span>
                            <span class="fa fa-star checked" id="second"></span>
                            <span class="fa fa-star checked" id="third"></span>
                            <span class="fa fa-star" id="fourth"></span>
                            <span class="fa fa-star" id="fifth"></span>
                            
                            <p class="card-text">
                              {{i.about}}<BR>Rent Price: {{i.rental_price}}</BR>
                              Deposit:{{i.deposit}}
                            </p>
                    </div>
                </div>
              </div>
            </div>
            {% endfor %}
                                    </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        </div>
    </body>

    </html>
</div>
</div>
</div>
</div>
</div>
</div>
</body>
{% endblock%}

User/templates/User/login.html
{% extends 'User/nonav.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'User/css/login.css' %}?{% now "U" %}">
{% endblock css %}
{% block content %}
<div class="container col-6 justify-content-center container1">
        <div class="container col-12 inner">
        <div class="container col-10">
                <div class="im">
                <img src="../../static/User/images/Prabandh.png" height="100px" width="100px"></img>
                </div>
                <h2 style="color: white;">Login </h2>
                <br>
        <form method="POST">
                {% csrf_token %}
                <div id="div_id_username" class="form-group">
                        <label for="id_username" class="requiredField down">
                                Username<span class="asteriskField">*</span> 
                        </label> 
                        <div class=""> 
                                <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="textinput textInput form-control" required id="id_username"> 
                        </div> 
                </div> 
                <br>
                <div id="div_id_password" class="form-group"> 
                        <label for="id_password" class="requiredField down">
                                Password<span class="asteriskField">*</span> 
                        </label> 
                        <div class=""> 
                                <input type="password" name="password" autocomplete="current-password" class="textinput textInput form-control" required id="id_password"> 
                        </div> 
                </div>
                <br>
                <div class="row">
                        <div class="col-2"></div>
                        <div class="col-2">
                                <button class="btn btn-danger" type="submit">LogIn</button>
                        </div>
                        <div class="col-4">
                        </div>
                        <div class="col-2">
                                <a href="{% url 'register' %}" class="btn btn-danger">SignUp</a>
                        </div>
                        <div class="col-2"></div>
                </div>
        </form> 
        </div>
        </div>
</div>
{% endblock %}

User/templates/User/logout.html
{% extends 'User/basic.html' %}
{% block content %}
<h1>
    Nikal jaa ab Bye
</h1>
{% endblock content %}

User/templates/User/nonav.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rental IT</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  {% block css %}
  {% endblock css %}
  <!-- <link rel="stylesheet" href="phone.css"> -->
</head>

  <body>
      {% block content %}
      {% endblock %}

        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

        {% block js %}
        {% endblock js %}
    </body>
</html>

User/templates/User/seller.html
{% extends 'User/basic.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
<link rel="stylesheet" href="{% static 'User/css/seller.css' %}?{% now "U" %}">
{% endblock css %}
{% block content %}
<div class="container">
        <div class="row top no-gutters justify-content-center">
                <div class="col-lg-5 col-sm-12 super">
                    <div class="col-lg-12 below-right no-gutters">
                    </div>
                    <div class="col-lg-12 cover-right no-gutters">
                        <div class='container hello'>
                                <h2 class='center-me'>Sell with Us</h2>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 left">
                    <div class="container-left container col-lg-12 col-sm-12">
                        <div class="container col-lg-10">
                            <div class="row register-heading">
                                <h3>Seller</h3>
                            </div>
                            <div class="row top-left side-row ">
                                <form method="POST">
                                        {% csrf_token %}
                                        <!-- {{ user|crispy }}
                                        {{ register|crispy }} -->
                                        <!-- {{ user.username.label }} -->    
                                        <div class="form-group">
                                                <div class="fieldWrapper">
                                                <label for="{{ user.name_of_business.id_for_label }}" class="down">Name of Business</label>
                                                {{ user.name_of_business }}
                                                </div>
                                                {{ user.name_of_business.errors }}
                                                <div class="fieldWrapper">
                                                <label for="{{ user.gst_no.id_for_label }}" class="down">GST_No</label>
                                                {{ user.gst_no }}
                                                </div>
                                                {{ user.email.errors }}
                                                <div class="fieldWrapper">
                                                <label for="{{ user.mobile_no.id_for_label }}" class="down">Mobile_No</label>
                                                {{ user.mobile_no }}
                                                </div>
                                                {{ user.password1.errors }}
                                                <div class="fieldWrapper">
                                                <label for="{{ user.city.id_for_label }}"class="down">City</label>
                                                {{ user.city }}
                                                </div>
                                                {{ user.password2.errors }}
                                                <div class="fieldWrapper">
                                                <label for="{{ user.PAN.id_for_label }}"class="down">PAN</label>
                                                {{ user.PAN }}
                                                </div>
                                                <br>
                                                <button class="btn btn-info" type="submit">Submit</button>
                                        </div>
                                </form> 
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
<!-- <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div id="div_id_name_of_business" class="form-group"> 
                <label for="id_name_of_business" class=" requiredField">
                        Name of business<span class="asteriskField">*</span> 
                </label> 
                <div class=""> 
                        <input type="text" name="name_of_business" class="form-control textinput textinput textInput form-control" maxlength="50" required id="id_name_of_business"> 
                </div>
        </div>
        <div id="div_id_gst_no" class="form-group"> 
                <label for="id_gst_no" class=" requiredField">
                        Gst no<span class="asteriskField">*</span> 
                </label> 
                <div class=""> 
                        <input type="text" name="gst_no" class="form-control textinput textinput textInput form-control" maxlength="15" required id="id_gst_no"> 
                </div> 
        </div> 
        <div id="div_id_mobile_no" class="form-group"> 
                <label for="id_mobile_no" class=" requiredField">
                        Mobile no<span class="asteriskField">*</span> 
                </label> 
                <div class=""> 
                        <input type="number" name="mobile_no" class="form-control textinput numberinput form-control" maxlength="10" required id="id_mobile_no"> 
                </div> 
        </div> 
        <div id="div_id_city" class="form-group"> 
                <label for="id_city" class=" requiredField">
                        City<span class="asteriskField">*</span> 
                </label> 
                <div class=""> 
                        <input type="text" name="city" class="form-control textinput textinput textInput form-control" maxlength="15" required id="id_city"> 
                </div> 
        </div> 
        <div id="div_id_PAN" class="form-group"> 
                <label for="id_PAN" class=" requiredField">
                        PAN<span class="asteriskField">*</span> 
                </label> 
                <div class=""> 
                        <input type="text" name="PAN" class="form-control textinput textinput textInput form-control" maxlength="10" required id="id_PAN"> 
                </div> 
        </div>

    
        <button class="btn btn-danger" type="submit">Submit</button>
    
</form>  -->
</div>
{% endblock %}