Prabandh/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('user/',include('User.urls')),
    path('',include('Rent.urls')),
    path('user/',include('User.urls')),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rent/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name="home"),
    path('product/',views.Productform,name="product"),
    path('ajax/load_subcat/', views.load_subcat, name='ajax_load_subcat'),
    path('cart/',views.cart,name="cart"),
    path('noti/',views.Issue,name="issue"),
    path('update/<my_id>',views.update,name="update"),
    path('issue/<my_id>',views.issueform,name="issueform"),
    path('rentedProduct', views.rentprod, name="rentprod"),
    path('Onrent', views.putrent, name="putrent"),
    path('cartdel/<my_id>',views.cartdel,name="cartdel"),
    path('cartadd/<my_id>',views.cartadd,name="cartadd"),
    path('Image/<prod_id>',views.Prod_view,name="Prod_view"),
    path("NewImage/",views.NewImage,name="NewImage"),
    path('event/<my_id>/<mysubcat>/<my_id1>',views.search_subcat,name="Search subcat"),
    path('Image/',views.load,name="load"),
    path('deleteImage/',views.deleteImage,name="Delete Image"),
    path('subcategory/<str:mysubcat1>/', views.search_subcat1, name="Search subcat1"),
    path('search/<my_id>', views.search_subcat1, name="search"),
    path('check/',views.Check.as_view(),name="check"),
    path('check/create/',views.create_payment,name="create"),
    path('webhook/',views.webhook,name="web"),
    path('success/',views.success.as_view(),name="success"),
    path('details/',views.RentAmt,name="detail"),
    path('booking/',views.rentprod,name="booking"),
    path('putrent/',views.putrent,name="putrent"),
    path('rate/<my_id>',views.rate,name="rate")
]

Rent/models.py
from django.db import models
from User.models import Seller
from django.contrib.auth.models import User

# Create your models here.

class Subcategory(models.Model):
    subcategories = models.CharField(max_length=50)
    Categories = models.ForeignKey("Category",on_delete=models.CASCADE)

    def __str__(self):
        return self.subcategories


class Category(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category
        
class Product(models.Model):

    seller_of_item=models.ForeignKey(Seller,related_name='seller_of_item', on_delete=models.CASCADE)
    availability=models.BooleanField(default=True)
    title=models.CharField(max_length=20)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    subcategory=models.ForeignKey(Subcategory,on_delete=models.SET_NULL, blank=True, null=True)
    rental_price=models.IntegerField()
    about=models.TextField()
    deposit=models.IntegerField()
    image_of_product=models.ImageField(upload_to='title_photos')

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

class Rent_Amount (models.Model):
    customer_of_item=models.ForeignKey(User,related_name='customer_of_item',on_delete=models.CASCADE)
    delivered_date=models.DateField()
    sent_date=models.DateField()
    related_product=models.OneToOneField(Product,related_name='rented_product',on_delete=models.CASCADE)
    payment=models.IntegerField()
    satisfaction=models.BooleanField(default=True)
    expected=models.DateField()

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

class Issues(models.Model):
    complainer=models.ForeignKey(User,related_name='complainer',on_delete=models.CASCADE)
    complain_against=models.ForeignKey(Product,related_name='complain_against',on_delete=models.CASCADE)
    issue=models.TextField()
    resolved=models.BooleanField(default=False)

class Photo (models.Model):
    photo=models.ImageField(upload_to='product_photos')
    product_photo=models.ForeignKey(Product, related_name='product_name', on_delete=models.CASCADE)


class Ratings(models.Model):
    rating_for_product=models.ForeignKey(Product, related_name='rating_for_product', on_delete=models.CASCADE)
    rating_by=models.ForeignKey(User, related_name='rating_by', on_delete=models.CASCADE)
    rating=models.FloatField()
    review=models.TextField()

class Bookings(models.Model):
    booking=models.OneToOneField(Product,on_delete=models.CASCADE)
    customer_who_booked=models.OneToOneField(User, on_delete=models.CASCADE)
    start_time=models.DateField()
    end_time=models.DateField()
    confirmation=models.BooleanField()

class Cart(models.Model):
    user=models.ForeignKey(User,related_name='user', on_delete=models.CASCADE)
    product_id=models.ForeignKey(Product,related_name='product_id', on_delete=models.CASCADE)
    def _str_(self):
        return self.product_id

Rent/forms.py
from django import forms
from .models import Product,Category,Subcategory,Photo,Rent_Amount,Issues,Bookings
from datetime import date

from django.contrib.auth.forms import UserCreationForm
class IssueForm(forms.ModelForm):
    class Meta:
        model=Issues
        exclude=('complainer','complain_against','resolved')

class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        exclude=('seller_of_item','availability')
        widgets={
        'title': forms.TextInput(attrs={'placeholder': 'Enter Product Title'}),
        'about': forms.Textarea(
            attrs={'placeholder': 'Enter description here'}),
       'Category' : forms.Select(attrs={'placeholder': 'Select Category'}),
        'rental_price': forms.NumberInput(
            attrs={'placeholder': 'Enter rent price(per day)'}),
        'deposit': forms.NumberInput(
            attrs={'placeholder': 'Enter deposit here(should be greater than rent price)'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subcategory'].queryset = Subcategory.objects.none()

        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['subcategory'].queryset = Subcategory.objects.filter(Categories_id=category_id).order_by('subcategories')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty subcategory queryset
        elif self.instance.pk:
            self.fields['subcategory'].queryset = self.instance.category.category_self.order_by('subcategories')


class PhotoForm(forms.ModelForm):
    
    class Meta:
        model = Photo
        exclude=('product_photo',)



class RentForm(forms.ModelForm):

    d=date.today()
    s=d.strftime("%y-%d-%m")
    
    class Meta:
        model = Rent_Amount
        widgets={
            'expected':forms.DateInput(attrs={'type':'date','class':'form-control date'})
        }
        fields=('expected',)

    
      

Rent/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.db.models import Min,Max
from django.views.generic import CreateView,TemplateView
from .models import Product,Photo,Subcategory,Category,Photo,Cart,Rent_Amount,Ratings,Issues
from User.models import Seller,User,Profile
from .forms import ProductForm,PhotoForm,RentForm,IssueForm,RentForm
from django.urls import reverse,resolve
from urllib.parse import urlencode
from django.conf import settings
import stripe
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import date,timedelta,datetime
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY





def cart(request):
    us = request.user
    Cartobj = (Cart.objects.filter(user=us)).values('product_id')
    print(Cartobj)
    prod = []
    j = 0
    for i in Cartobj:
        j = j + 1
    print(j)
    for i in range(0, j):
        prod = prod + list(Cartobj[i].values())
    print(prod)
    sum = 0
    products = Product.objects.filter(id__in=prod)
    for i in products:
        sum = sum + i.deposit

    request.session['total']=sum
    param = {
        'product': products,
        'sum': sum,
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
    }
    print(products)
    return render(request, 'Rent/subcstfil.html', param)


def cart(request):

    if request.method=='POST':
        my_items = Cart.objects.filter(user=request.user)
        print(my_items)
        total = 0
        d=date.today()
        s=d.strftime("%Y-%m-%d")
        r=Rent_Amount.objects.all()
        listw=[]
        for y in r:
            listw.append(y.related_product)
        
        print(listw)
        print(s)
        for p in my_items:
            if p.product_id not in listw:
                print(p)
                form=RentForm(request.POST)
                unsave=form.save(commit=False)
                u=form.cleaned_data['expected']
                unsave.related_product=p.product_id
                unsave.customer_of_item=request.user
                print(request.session['total'])
                unsave.payment=request.session['total']
                unsave.delivered_date=s
                unsave.sent_date=u
                unsave.save()
                print("ll")              

        
        return redirect('check')





    user = request.user
    Cartobj=(Cart.objects.filter(user=user)).values('product_id')
    print(Cartobj)
    prod=[]
    j=0
    for i in Cartobj:
        j=j+1
    print(j)
    for i in range(0, j):
        prod=prod+list(Cartobj[i].values())
    print(prod)
    sum=0
    products = Product.objects.filter(id__in=prod)
    
    for i in products:
        sum=sum+i.deposit

    request.session['total']=sum

    u = User.objects.get(username=user)
    isSeller=Profile.objects.get(user=u).seller

    print(isSeller)
    param = {
        'product': products,
        'sum':sum,
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY,
        'us':isSeller,
        'form':RentForm
    }
    print(products)
    return render(request, 'User/cart.html', param)


def rentprod(request):
    us = request.user
    RentPr = Rent_Amount.objects.filter(customer_of_item=us).values('related_product')
    RentProd=RentPr.values('related_product')

    print(RentProd)
    prod = []
    j = 0
    for i in RentProd:
        j = j + 1
    print(j)
    for i in range(0, j):
        prod = prod + list(RentProd[i].values())
    print(prod)
    sum = 0
    products = Product.objects.filter(id__in=prod)
    param = {
        'product': products,
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
    }
    return render(request, 'Rent/subcstfil.html', param)

def putrent(request):
    us = request.user
    u = Seller.objects.get(seller=us)
    products = Product.objects.filter(seller_of_item=u)
    param = {
        'product': products,
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
    }
    return render(request, 'Rent/subcstfil.html', param)


def cartadd(request, my_id):
    us = request.user
    prod = Product.objects.get(id=my_id)
    cart1=Cart.objects.filter(user=us, product_id=prod).exists()
    if cart1!=True:
        b = Cart(user=us, product_id=prod)
        b.save()
    return redirect('cart')


def cartdel(request, my_id):
    Cart.objects.filter(product_id=my_id).delete()
    return redirect('cart')


def search_match(query, item):
    if query in item.title.lower() or query in item.about.lower():
        return True
    else:
        return False


def index(request):
    k=0
    if request.user.is_authenticated:
        us = request.user
        k = 0
        sell = Seller.objects.filter(seller=us).exists()
        if sell == True:
            u = Seller.objects.get(seller=us)
            product = (Product.objects.filter(seller_of_item=u)).values('id')
            print(product)
            prod = []
            j = 0
            for i in product:
               j = j + 1
            print(j)
            for i in range(0, j):
                prod = prod + list(product[i].values())
            print(prod)
            print("Hello")
            rentamount = Rent_Amount.objects.filter(related_product_id__in=prod, satisfaction=False)
            print(rentamount)
            print("Hello1")
            product1 = {}
            for r in rentamount:
                prod = Issues.objects.filter(complain_against=r.related_product, complainer=us).exists()
                if r.delivered_date <= date.today() and prod!=True:
                    print(r.related_product_id)
                    k = k + 1
                    product1 = Product.objects.filter(id=r.related_product_id)

        product2 = {}
        rentamount = Rent_Amount.objects.filter(customer_of_item=us)
        for r in rentamount:
            prod = Ratings.objects.filter(rating_for_product=r.related_product, rating_by=us).exists()
            if r.sent_date <= date.today() and prod != True:
                product2 = Product.objects.filter(id=r.related_product_id)
                k = k + 1
        product3 = {}
        rentamount = Rent_Amount.objects.filter(customer_of_item=us)
        print(rentamount)
        for r in rentamount:
            print(r.delivered_date)
            print(date.today() + timedelta(days=1))
            if r.sent_date == (date.today() + timedelta(days=1)):
                print(date.today() + timedelta(days=1))
                product3 = Product.objects.filter(id=r.related_product_id)
    param = {
        'k':k,
    }
    return render(request, 'Rent/home_page.html', param)


def search_subcat(request, my_id, mysubcat,my_id1):
    if my_id == '1':
        test = {
            'Clothes': ['Ethnic', 'Western', 'Jackets', 'Denims'],
            'Car': ['Swift', 'Audi', 'Sedan', 'Mercedes'],
        }
    elif (my_id == '2'):
        test = {
            'Formals': ['Ethnicity', 'Sweatshirts', 'Jacket', 'Hoodies', ],
            'Decorations': ['Posters', 'Balloons', 'Streamers', 'Party Hats'],
        }
    elif (my_id == '3'):
        test = {
            'Essentials-1': ['Flowers', 'Chandeliers', 'Paper decor', 'Fairy Lights', ],
            'Essentials-2': ['LED Diyas', 'Electric Lamps', 'Photo Frames', 'Wall Decor'],
        }
    category = get_object_or_404(Subcategory, subcategories=mysubcat)
    products = Product.objects.filter(subcategory=category,availability=True)
    if my_id1 == '2':
        min2 = ''
        min1 = request.GET.get('min-value')
        for i in min1:
            if i == ',':
                pass
            else:
                min2 = min2 + i
        min = int(min2)
        max2 = ''
        max1 = request.GET.get('max-value')
        for i in max1:
            if i == ',':
                pass
            else:
                max2 = max2 + i
        max = int(max2)
        print(min)
        print(max)
        products = Product.objects.filter(subcategory=category, rental_price__range=(min, max),availability=True)
    min_price = products.aggregate(Min('rental_price'))
    max_price = products.aggregate(Max('rental_price'))
    price = {**min_price, **max_price}
    print(price)
    print(min_price)
    context = {
        'test': test,
        'my_id': my_id,
        'product': products,
        'price': price,
        'mysubcat':mysubcat,

    }
    return render(request, 'Rent/Weddings.html', context)


def search_subcat1(request,my_id=''):
    query = request.GET.get('search')
    products=Product.objects.filter(availability=True)
    if my_id == '2':
        min2 = ''
        min1 = request.GET.get('min-value')
        for i in min1:
            if i == ',':
                pass
            else:
                min2 = min2 + i
        min = int(min2)
        max2 = ''
        max1 = request.GET.get('max-value')
        for i in max1:
            if i == ',':
                pass
            else:
                max2 = max2 + i
        max = int(max2)
        print(min)
        print(max)
        products = Product.objects.filter(rental_price__range=(min, max),availability=True)
    products = [item for item in products if search_match(query, item)]
    return render(request, 'Rent/prod.html', {'products': products})


def Event(request, my_id='', my_id1='0'):
    # subcat_01=['Ethnic','Drum','Gifts','Car',]
    # subcat_02=['Swift','Audi','Sedan','Mercedes']
    if my_id=='1':
        test={
            'Clothes': ['Ethnic','Western','Jackets','Denims'],
            'Car': ['Swift','Audi','Sedan','Mercedes'],
        }
    elif (my_id == '2'):
        test = {
            'Formals': ['Ethnicity', 'Sweatshirts', 'Jacket', 'Hoodies', ],
            'Decorations': ['Posters', 'Balloons', 'Streamers', 'Party Hats'],
        }
    elif (my_id == '3'):
        test = {

Rent/templates/Rent/ProdView.html
{% extends 'User/basic.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'Rent/css/ProdView.css' %}?{% now "U" %}">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">

{% endblock %}
{% block title%}
    {{Product.product_name}}
{%endblock%}
{% block content %}
<div class="container-fluid">
    <br>
    <div class="row">
        <h2>Product Details</h2>
        <br>
        <br>
        <br>
        <div class="col-sm-5 left1">
            <div class="col-12 left">
                {% include 'Rent/loop.html' %}
            </div>
        </div>
        <div class="col-sm-1"></div>
        <div class="col-sm-5 right col-xs-12">
            <div class="row">
                <div class="col-12">
                    <br>
                    <div class="row justify-content-center">
                        <div class="col-6">
                            <h3>{{ pro.title }}</h3>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-5">
                            <h5>Product Description</h5>
                        </div>
                        <div class="col-7">
                            <div class="aboutblock">
                                <h5>{{ pro.about }}</h5>
                            </div>
                            <br>
                            <form method="POST" class="photoform" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <h4 for="id_photo"><strong>Add more Images?</strong></h4>
                                </div>
                                <br>
                                <div class="row filecon container-fluid">
                                    <div class="col-4 imagecover h-100">
                                        <input type="file" name="photo" accept="image/*" required id="id_photo" class="imagefile" onchange="bg(event)">
                                        <div class="drag">
                                            <h3>Drag Your image here</h3>
                                        </div>
                                    </div>
                                    <div id="im" class="inactive">
                                        <img id="o">
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-sm">
                                        <button class="btn btn-info file" data-val="{{ pro.id }}" type="submit">Submit</button>
                                    </div>  
                                    <div class="forbtn col-sm">
                                        <button class="btn btn-danger removeb d-none" onclick="remove(event)" type="text">Remove</button>
                                    </div>
                                    <div class="col-sm product">
                                        <a href="{% url 'product' %}" class="btn btn-info">Product</a>             
                                    </div>           
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                    <!-- <div class="col-6">
                        <h4>{{ pro.about }}</h4>
                        <form method="POST" class="photoform" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ pform }}
                            <br>
                            <button class="btn btn-info file" data-val="{{ pro.id }}">Submit</button>
                        </form>
                        <button class="btn btn-info"> Add new Product</button>
                    </div> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    <script>
        $(document).ready(function(){
            $('.photoform').submit(function(e){
                e.preventDefault();
                console.log("LLLL");
                var w=$('.file').data('val');
                var fdata=new FormData(this);
                fdata.append("blog",JSON.stringify(w));
                console.log(fdata);
                var csrftoken = $("[name=csrfmiddlewaretoken]").val();
                console.log(fdata);
                $.ajax({
                     type: "post",
                     url: "{% url 'NewImage' %}",
                     headers:{
                        "X-CSRFToken": csrftoken
                    },
                     data:fdata,
                     contentType: false,
                     processData: false,
                     enctype: 'multipart/form-data',
                     success: function (response) {
                        $(".left").html('').load(
                            "{% url 'load' %}"
                        ).fadeIn(500);
                        document.getElementById("id_photo").value="";
                        $(".inactive").hide();
                        $(".removeb").addClass("d-none");
                        $(".imagecover").show();
                        $(".product").show();
                     }
                 });
            })
        })

       $(document).ready(function(){
            $(document).delegate(".delete","click",function () { 
                console.log("kkk");
                var w=$(this).data('val');
                var w1=$('.file').data('val');
                console.log(w+""+w1);
                $.ajax({
                    type: "post",
                    url: "{% url 'Delete Image' %}",
                    data: {
                        ph_id:w,
                        p_id:w1,
                        csrfmiddlewaretoken:"{{csrf_token}}",
                    },
                    dataType: "json",
                    success: function (response) {
                        $(".left").html('').load(
                            "{% url 'load' %}"
                        ).fadeIn(500);
                    }
                });
             })
       })
    </script>
    <script src="{% static 'Rent/js/ProdView.js' %}?{% now "U" %}"></script>
{% endblock %}

Rent/templates/Rent/Product.html
{% extends 'User/basic.html' %}
{% load crispy_forms_tags %}
{% block css %}
{% load static %}
<style>
body{
background-color: #FFCC99;
}
.hello {
  background-color:white;
  background-position: center;
  background-size: cover;
  border-radius:20px;
}
@media(min-width:499px) and (max-width:799px){
.hello {
  margin-top:50px;
  }
}
@media(min-width:800px) {
.hello {
  margin-top:50px;
  width:800px;
  }
}
textarea{
height:100px;
}
label{
font-weight:500;
}
select{
 width:300px;
 }

</style>

{% endblock %}
{% block content %}
<div class="container hello">
        <center><h2>Register your product/service</h2></center>
<form method="POST" enctype="multipart/form-data" id="perform" data-subcat-url="{% url 'ajax_load_subcat' %}">
        {% csrf_token %}
        {{ form|crispy }}
       <br/> <center><button class="btn btn-primary" type="submit">Submit</button></center>
</form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_category").change(function () {
        const url = $("#perform").attr("data-subcat-url");
        console.log('Hello');
        const CategoryId = $(this).val();  // get the selected category ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,
            data: {
                'CategoryId': CategoryId
            },
            success: function (data) {
                $("#id_subcategory").html(data);  // replace the contents of the subcat input with the data that came from the server
            }
        });
    });
</script>
{% endblock %}

Rent/templates/Rent/booking.html
{% extends 'User/basic.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'Rent/css/booking.css' %}?{% now "U" %}">

Rent/templates/Rent/cancel.html
<h1>Cancel</h1>

Rent/templates/Rent/checkout.html
{% extends 'User/basic.html' %}
{% load static %}
{% block headjs %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'Rent/js/checkout.js' %}?{% now "U" %}" defer></script>
{% endblock %}


{% block css %}
<link rel="stylesheet" href="{% static 'Rent/css/checkout.css' %}?{% now "U" %}"/>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <!-- Just Checking -->
  <div class="row top no-gutters justify-content-center">
      <div class="col-lg-5 col-sm-12 super">
          <div class="col-lg-12 below-right no-gutters">
          </div>
          <div class="col-lg-12 cover-right no-gutters">
              <div class='container hello'>
                <div class="center-me">
                  <h2>To Pay -{{ total }}</h2>
                  <br>
                  <h2>Hope you enjoy buying with us</h2>
                </div>
              </div>
              <h1></h1>
          </div>
      </div>
      <div class="col-lg-5 left">
          <div class="container-left container col-lg-12 col-sm-12">
              <div class="container col-lg-10">
                  <div class="row register-heading">
                      <h3>Last Step</h3>
                  </div>
<!--                  <div class="row register-heading">-->
<!--                      <h3>Last Step</h3>-->
<!--                  </div>-->
                  <div class="row top-left side-row ">
                    <form id="payment-form">
                      <div id="payment-element">
                      </div>
                      <button class="btn btn-primary" id="submit">
                        <div class="spinner hidden" id="spinner"></div>
                        <span id="button-text">Pay now</span>
                      </button>
                      <div id="payment-message" class="hidden"></div>
                    </form>
                    {% csrf_token %}
                  </div>
              </div>
          </div>
      </div>
  </div>  
</div>
















{% endblock %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Accept a payment</title>
    <meta name="description" content="A demo of a payment on Stripe" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
  </head>
  <body>
    <!-- Display a payment form -->
    
  </body>
</html>

Rent/templates/Rent/details.html
{% extends 'User/basic.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Hellos</h1>
    <form>
        {{form|crispy}}
    </form>
{% endblock %}

Rent/templates/Rent/issues.html
{% extends 'User/basic.html' %}
{% load crispy_forms_tags %}
{% block css %}
{% load static %}
<style>
     .hello {
  background-color:white;
  background-position: center;
  background-size: cover;
  border-radius:20px;
}
@media(min-width:499px) and (max-width:799px){
.hello {
  margin-top:50px;
  }
}
@media(min-width:800px) {
.hello {
  margin-top:50px;
  width:800px;
  }
}

body{
background-color:darkblue;
}
textarea{
height:100px;
}
label{
font-weight:500;
}
select{
 width:300px;
 }

</style>

{% endblock %}
{% block content %}
<div class="container hello">
        <center><h2>Raise your Issue</h2></center>
<form method="POST" enctype="multipart/form-data" id="perform" data-subcat-url="{% url 'ajax_load_subcat' %}">
        {% csrf_token %}
        {{ form|crispy }}
       <br/> <center><button class="btn btn-primary" type="submit">Submit</button></center>
</form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

{% endblock %}

Rent/templates/Rent/loop.html
<!-- {% for p in Product %}
<div class="imgb">
    <img src="{{ p.photo.url }}">
</div>
{% endfor %} -->
<!-- <div class="col-5 left"> -->
    <div class="col-12 k">
        <!-- <h1>{{ pro.image_of_product.url }}</h1> -->
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ pro.image_of_product.url }}" class="d-block w-100" alt="...">
                        <div class="over">
                            <div class="vertical-center">
                                <button class="btn btn-danger delete" data-val="{{ p.id }}">Delete</button>
                            </div>
                        </div>
                    </div>
                    {% for p in Product %}
                        <div class="carousel-item">
                            <img src="{{ p.photo.url }}" class="d-block w-100" alt="...">
                            <div class="over">
                                <div class="vertical-center">
                                    <button class="btn btn-danger delete" data-val="{{ p.id }}">Delete</button>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        <!-- <div class="outerimg"> -->
            <!-- <div class="imgb">
                <img src="{{ p.photo.url }}">
                <div class="over">
                    <div class="vertical-center">
                        <button class="btn btn-danger delete" data-val="{{ p.id }}">Delete</button>
                    </div>
                </div>
            </div> -->
        <!-- </div> -->
    </div>
<!-- </div> -->